
[[introduction]]
[.preface]
== Introduction

The ISO 10303 series of international standards describe the computer-interpretable
representation of product information the exchange of product data. The objective is
to provide a neutral mechanism capable of describing products throughout their life
cycle. This mechanism is suitable not only for neutral file exchange, but also as a
basis for implementing and sharing product databases, and as a basis for retention
and archiving.

This document is a member of the application protocol series. This document specifies
an application protocol (AP) for <AP_purpose>.

This document defines the context and scope for <AP_purpose>, and references the AP
module (<<module_cover,AP module reference>>) that specifies the information requirements for <AP_purpose>,
and the integrated resources necessary to satisfy those requirements.

Application protocols provide the basis for developing implementations of ISO 10303
and abstract test suites for the conformance testing of AP implementations.

<<scope>> defines the scope of the application protocol and summarizes the
functionality and data covered. 

An application activity model that is the basis for the definition of the scope is
provided in <<annex_aam>>.
 
<<defs_3>> lists the terms defined in this document and refers to
terms defined elsewhere.  

This document describes the high level business concepts and terminology of the
application and specifies the implementation conformance options. 

<<info_reqs_4-2>> presents the business context for the
information requirements. It also contains a data planning model, which provides
an overview of the information requirements of this domain in domain terminology.
<<info_reqs_4-3>> includes a reference to the AP module
(<<module_cover,AP module reference>>), which specifies the details
of the information requirements of the application.

Resource constructs are interpreted to meet the information requirements.

The interpretation is specified in the AP module (<<module_cover,AP module reference>> that is referenced
in <<main_5>>. This interpretation shows the correspondence between the information
requirements and the module interpreted model (MIM). The short listing of the MIM that
specifies the interface to the integrated resources is included by reference from the
AP module. The expanded listing of the MIM that is referenced in <<annex_exp_lf>> contains
the complete EXPRESS for the MIM without annotation.
   
<<cls_6>> specifies subsets of the AP against which conformance can be claimed.
  
Additional requirements for specific implementation methods are given in <<annex_imp_meth>>.

// Your text here


// Insert the following statement if patent rights have been identified:
////
The International Organization for Standardization (ISO) draws attention to the fact
that it is claimed that compliance with this document may involve the use of a patent.

ISO takes no position concerning the evidence, validity and scope of this patent right.
The holder of this patent right has assured ISO that he/she is willing to negotiate
licences under reasonable and non-discriminatory terms and conditions with applicants
throughout the world. In this respect, the statement of the holder of this patent right
is registered with ISO. Information may be obtained from the patent database available
at www.iso.org/patents.

Attention is drawn to the possibility that some of the elements of this document may be
the subject of patent rights other than those in the patent database. ISO shall not be
held responsible for identifying any or all such patent rights.
////

A detailed description of the changes is provided in <<annex_changes>>.