
== Information requirements

=== General

This clause specifies the information required for <AP purpose>
The information requirements are defined using the terminology
of the subject area of this application protocol. 

[NOTE]
The information requirements correspond to those of the activities identified as
being within the scope of this application protocol in <<annex_aam>>.

[[info_reqs_4-2]]
=== Business concepts and terminology

This subclause describes the business context for the information required
for <AP purpose>.
       
// insert text here


[[info_reqs_4-3]]
=== Information requirements model

==== Model overview

This subclause contains a business overview of the requirements contained in
the AP module (<<ap-module-ref,AP module reference>>) as represented in the following list of modules.

The detailed information requirements for this AP are defined in the
AP module (<<ap-module-ref,AP module reference>>.

[NOTE]
The ARM EXPRESS(((index_arm_express,index))) contains a complete list of all ARM
objects identified in the information requirements in the AP module (<<ap-module-ref,AP module reference>>).


[NOTE]
The module(((index_arm_modules,index))) contains a complete list of all the
modules used in the ARM of this document. 
