= ISO/TC 184/SC 4 boilerplate content in Metanorma format

== Purpose

This repository provides
https://www.iso.org/committee/54158.html[ISO/TC 184/SC 4]
boilerplate content in the Metanorma AsciiDoc format.

The data source for this repository is:

* https://sd.iso.org/bitbucket-pilot/projects/ISOTC184SC4/repos/boilerplate[the official "ISO/TC 184/SC 4 boilerplate" repository (public)]

== Reference documents

* ISO Simple template
* ISO/IEC Directives, Part 2
* SC 4 Supplementary directives

Any issues or questions regarding the boilerplate shall be reported to the SC 4
Quality Committee.

== Contents

* `iso-8000` contains a template that contains boilerplate content for
  deliverables of the ISO 8000 series.

NOTE: Other boilerplate content will be offered when ready.

== Reference

Please refer to https://www.metanorma.org on how to use this repository.

////
The `ISO` folder only apply to the developers of supporting tools like STEPmod and STEPlib.

The ISO folder contains:
- Boilerplate which is copied from the ISO Simple template.
- 3 grey logos if we need to use ISO logo for the html publication.

The ISO_TC184_SC4 folder contains:
- the required boilerplate text for the SC 4 documents.

Then each series folder contains:
- the boilerplate text for the series.

For all our documents, the SC 4 fragments apply.
For all our series documents the series fragment, if any, replaces the SC 4 fragment.

Example:

- In ISO 10303, the first element of the scope for an application protocol is defined in the fragment 10303_AP_Scope-1.txt in the ISO_10303/AP folder.

This fragment has to be used in place of the SC4_Scope-1.txt for the 10303 application protocol documents.

Then, SC4_Scope-2.txt and SC4_Scope-3.txt are used.

- Therefore, ISO 10303 application protocol scope is composed of 10303_AP_Scope-1.txt, followed by SC4_Scope-2.txt and SC4_Scope-3.txt.  SC4_Scope-3.txt is conditional.

In ISO 8000 we use the SC 4 required text without changes.

- Therefore, the ISO 8000 scope is composed of SC4_Scope-1.txt, followed by SC4_Scope-2.txt and SC4_Scope-3.txt. SC4_Scope-3.txt is conditional.

All the references to the files are relative to this repository.

== 10303 replacement strings (provided in the files between angle brackets)

|===
| string |	example

| AP module reference
|	example: ISO/TS 10303-410

| AP purpose
|	example: the use of the integrated resources necessary for the scope and
information requirements for the design of electronic assemblies, interconnect
and packaging.

| AP name
|	example: Electronic assembly, interconnect and packaging design

| AP schema
|	example: Ap210_electronic_assembly_interconnect_and_packaging_design schema

| MIM LF name
|	example: AP210_ELECTRONIC_ASSEMBLY_INTERCONNECT_AND_PACKAGING_DESIGN_MIM_LF

| schema identification
|	example: 1 0 10303 410 5 1 4

|===
////
